# .github/workflows/preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Install dependencies
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material ipykernel nbconvert traitlets jupytext pandas python-markdown-math mkdocs-simple-hooks pillow cairosvg matplotlib scipy plotly ipywidgets
      - name: Build site
      - run: mkdocs build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: pr-preview
          source-dir: ./site/
